//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAuctionWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBuyerMaster
    {
        public int BuyerId { get; set; }
        public string BuyerFirstName { get; set; }
        public string BuyerLastName { get; set; }
        public string BuyerEmailId { get; set; }
        public int BuyerState { get; set; }
        public int BuyerCity { get; set; }
        public string BuyerAddress { get; set; }
        public string BuyerPincode { get; set; }
        public string BuyerMoileNo { get; set; }
        public int BidAmount { get; set; }
        public Nullable<int> BuyersProductId { get; set; }
    }
}
